#!/usr/bin/perl

$num_args = $#ARGV + 1;
if ($num_args != 3) {
    print "Usage: db-transfer <src_path> <dest_path> <database_name>\n";
        exit;
}

my $tempDir = "/tmp";

my $srcFilename = $ARGV[0];
my $destFilename = $ARGV[1];
my $dbName = $ARGV[2];


local $/=undef;
open FILE, $srcFilename or die "Couldn't open file: $!";
$source = <FILE>;
close FILE;

my @srcLines = split /\n/, $source;

my $linesToAdd;
my $dbFound = 0;
my $addText = 0;

foreach my $srcLine (@srcLines) {
  #Read db-name
  if($srcLine =~ /<database-name>$dbName<\/database-name>/) {
    $dbFound=1;
  }
  if($addText) {
    $linesToAdd .= $srcLine;
    $linesToAdd .= "\n";
  }
  if((($srcLine =~ /<\/forests>/) || ($srcLine =~ /<forests\/>/)) && ($dbFound)) {
    $addText=1;
  }
  if(($addText) && ($srcLine =~ /<\/database>/)) {
    last;
  }
}

if($dbFound == 0) {
  print "$dbName does not exist in $srcFilename\n";
  exit 1;
}

$source = ();
@srcLines = ();

local $/=undef;
open FILE, $destFilename or die "Couldn't open file: $!";
$dest= <FILE>;
close FILE;

# Copy to backup
($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst) = localtime();
#$timestamp = chomp($timestamp);
`cp $destFilename $tempDir/database$mday$hour$min$sec.xml`;
print "Copied $destFilename to $tempDir/databases$mday$hour$min$sec.xml\n";

my @destLines = split /\n/, $dest;

my $priorToDB;
my $afterDB;
my $toWriteOut;
my $copyForDestPre = 1;
my $copyForDestPost= 0;
my $destDbFound = 0;
my $destForestEnd = 0;

$count = 1;
foreach my $destLine (@destLines) {
  $count += 1;
  if($destLine =~ /<database-name>$dbName<\/database-name>/) {
    $destDbFound = 1;
  }
  if($copyForDestPre) {
    $priorToDB .= $destLine;
    $priorToDB .= "\n";
  }
  if((($destLine =~ /<\/forests>/) || ($destLine =~ /<forests\/>/)) && ($destDbFound)) {
    $destForestEnd = 1;
    $copyForDestPre = 0;
  }
  if($copyForDestPost) {
    $afterDB .= $destLine;
    $afterDB .= "\n";
  }
  if(($destLine =~ /<\/database>/) && ($destDbFound)) {
    $copyForDestPost = 1;
  }
}

if($destDbFound == 0) {
  print "$dbName does not exist in $destFilename\n";
  exit 1;
}

# print "prior to DB: \n$priorToDB";
# print "Lines to add:\n$linesToAdd";
# print "after DB: \n$afterDB";

open(my $filehandle, '>', $destFilename) or die "Could not open file '$destFilename' $!";

print $filehandle $priorToDB;
print $filehandle $linesToAdd;
print $filehandle $afterDB;

close $filehandle;

print "Completed copying $dbName from $srcFilename to $destFilename\n";
