#!/usr/bin/python

import sys
import webbrowser
from subprocess import call

if len(sys.argv) < 2:
	print "Missing search term, exiting"
	sys.exit(1)


query=""
documentationSrvr="http://localhost:8011/do-search?v=8.0&api=1&q="
listsSrvr="https://lists.marklogic.com/search/?q="
google="https://www.google.com/?gws_rd=ssl#q="
marklogicKeyword="marklogic+"
knowledgebase="marklogic+knowledgebase+support+"
supporttools="http://supporttools.marklogic.com/tickets?query="

first=True

for arg in sys.argv: 
   if first == True: 
	first=False
        continue
   query+= '"' + arg + '"' + " " 

queryWithPlus=query.replace(" ","+")
queryWithPlus=queryWithPlus[:-1]
# Get String, Surround with '"' and append with space
# Find and replace space with necessary char
webbrowser.open_new(google+queryWithPlus )
webbrowser.open_new(google+knowledgebase+queryWithPlus )
webbrowser.open_new(google+marklogicKeyword+queryWithPlus)
webbrowser.open_new(supporttools+queryWithPlus)
webbrowser.open_new(listsSrvr+queryWithPlus)
webbrowser.open_new(documentationSrvr+queryWithPlus)
