#!/usr/bin/python

import re
import sys
from subprocess import check_output,call


if len(sys.argv) < 3:
	print "Missing commands, exiting"
	print "Ex:"
	print "     sd-uploader <Ticket ID> <Filename>"
	sys.exit(1)

username=check_output("whoami")

properties="/Users/" + username.rstrip() + "/.sd-uploader.prop"
propFile  =open(properties, "r")
server=propFile.read().rstrip()

call(["scp","/Users/" + username.rstrip() +"/Downloads/"+sys.argv[2],server+":/tmp/"])

call(["ssh",server,"/var/opt/bin/support-dump.pl -ticket "+sys.argv[1]+" -file /tmp/"+sys.argv[2]+" -uri http://supporttools.marklogic.com"])
